// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TeamServer.Infrastructure.Data;

#nullable disable

namespace TeamServer.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251021064145_addedSetter")]
    partial class addedSetter
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TeamServer.Domain.Entities.Listeners.HttpListeners.HttpListenerEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("BindPort")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("HttpListeners", null, t =>
                        {
                            t.HasCheckConstraint("CK_HttpListener_BindPort", "[BindPort] BETWEEN 1024 AND 65535");
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
