// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TeamServer.Infrastructure.Data;

#nullable disable

namespace TeamServer.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260106050626_UpdateAgentProperty")]
    partial class UpdateAgentProperty
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TeamServer.Domain.Entities.Agents.Agent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("LastSeen")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("UniqueId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UniqueId")
                        .IsUnique();

                    b.ToTable("Agents", (string)null);
                });

            modelBuilder.Entity("TeamServer.Domain.Entities.Listeners.HttpListeners.HttpListenerEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("BindPort")
                        .HasColumnType("int");

                    b.Property<int>("ListenerStatus")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("HttpListeners", null, t =>
                        {
                            t.HasCheckConstraint("CK_HttpListener_BindPort", "[BindPort] BETWEEN 1024 AND 65535");
                        });
                });

            modelBuilder.Entity("TeamServer.Domain.Entities.Agents.Agent", b =>
                {
                    b.OwnsOne("TeamServer.Domain.Entities.Agents.AgentMetadata", "Metadata", b1 =>
                        {
                            b1.Property<Guid>("AgentId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Architecture")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("Hostname")
                                .IsRequired()
                                .HasMaxLength(30)
                                .HasColumnType("nvarchar(30)");

                            b1.Property<string>("Integrity")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<int>("ProcessId")
                                .HasColumnType("int");

                            b1.Property<string>("ProcessName")
                                .IsRequired()
                                .HasMaxLength(30)
                                .HasColumnType("nvarchar(30)");

                            b1.Property<string>("Username")
                                .IsRequired()
                                .HasMaxLength(30)
                                .HasColumnType("nvarchar(30)");

                            b1.HasKey("AgentId");

                            b1.ToTable("Agents");

                            b1.WithOwner()
                                .HasForeignKey("AgentId");
                        });

                    b.Navigation("Metadata")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
